### ISSUE TITLE
二级界面及截图功能

### ISSUE THREAD

**Issue by zx20085121996** [anobaka/InsideWorld#121]
- 增加二级界面，选中资源优先进入二级界面，现实缩略图、介绍、tag信息等，二级界面中点击播放再调用相关程序

~~- 资源界面支持手动更换截图，手动编辑信息~~

~~- 资源界面支持运行或者打开资源时截图为封面~~

**Comment by anobaka** [comment]
封面相关功能已拆分至 #156

**Comment by anobaka** [comment]
功能预览：
![resource-detail-editing1](https://user-images.githubusercontent.com/2888789/170434261-0e9f2075-21c4-4427-9ad3-6c7b43ab6e73.png)
![resource-detail-editing2](https://user-images.githubusercontent.com/2888789/170434262-7bcfcd94-fa6d-4031-97ec-ea2eeee8eb4d.png)
