### ISSUE TITLE
白畫面無法操作

### ISSUE THREAD

**Issue by bennyz327** [anobaka/InsideWorld#172]
**Describe the bug**
打開任一資源的編輯頁面，按下原作或是標籤列表右邊的編輯圖示會讓畫面進入一個全白的狀況，只有關閉程式重新開啟才會恢復，請問這樣是正常的嗎?

截圖
1.按下這兩個圖示
![螢幕擷取畫面 2022-06-26 220510](https://user-images.githubusercontent.com/96097874/175818208-2a2d4475-dbf9-4063-a83f-4189d9596aa0.png)

2.會變成全白畫面
![螢幕擷取畫面 2022-06-26 220530](https://user-images.githubusercontent.com/96097874/175818237-d6a42856-13ab-49bc-9d40-28ff6ba278e8.png)

3.右鍵開發工具內的錯誤訊息
![螢幕擷取畫面 2022-06-26 220750](https://user-images.githubusercontent.com/96097874/175818255-bfb09362-c570-4128-bff4-d9170fbf3a2d.png)

OS: Windows 10
Version: 1.6.0-rc2

**Comment by anobaka** [comment]
已复现，v1.6.0修复
