### ISSUE TITLE
可以为不同类型的文件设置不同的播放器

### ISSUE THREAD

**Issue by anobaka** [anobaka/InsideWorld#182]
需要确认：
1. 是否有一种需求，在不同分类下使用不同的软件打开同一个类型的文件？

也许可以直接通过使用`自启动播放器/系统播放器/SelfPlayer`作为全局播放器

**Comment by bennyz327** [comment]
我遇到使用上的問題是
若在一個資料夾中有不同類型的檔案時(例如有 zip 和 影片 )
會導致其中一方類型無法讀取，因為在設定分類的播放器只能選擇一個撥放器
必須去破壞原本整理的資料夾結構，把圖片影片分開2個資料夾才能讓2方在應用程式中都能進行播放動作

**Comment by anobaka** [comment]
> 我遇到使用上的問題是 若在一個資料夾中有不同類型的檔案時(例如有 zip 和 影片 ) 會導致其中一方類型無法讀取，因為在設定分類的播放器只能選擇一個撥放器 必須去破壞原本整理的資料夾結構，把圖片影片分開2個資料夾才能讓2方在應用程式中都能進行播放動作

@bennyz327 假设你的资源的文件结构和意图如下：
```
|--媒体库根目录A
    |--资源1
         |--a.zip    // 需要播放
         |--a.mp4    // 需要播放
         |--a.mp3    // 不需要播放
         |--封面图.png
    |--其他资源...
```

目标：
1. `资源1`在资源列表会作为**一个**资源展示，并使用`封面图.png`作为封面；
2. `a.zip`和`a.mp4`可播放，`a.mp3`不可播放；

需要做的设置：
1. 将`媒体库根目录A`设置为媒体库的根目录
2. 在媒体库中选择`第一层`目录作为资源筛选规则；
3. 配置一个自定义`可播放文件查找器`，把`.zip`和`.mp4`都加进去，并将该`可播放文件查找器`关联至对应`分类`中；
4. 设置该分类播放器为`自启动播放器/SelfPlayer`，这个是跟随系统（OS）而定的，会直接使用你在系统级别配置的播放器；

**Comment by bennyz327** [comment]
是的，我有那樣嘗試過

但是平常在檔案總管中打開zip時，我希望能以預設的Bandizip之類的壓縮軟體打開zip
而在軟件中，則希望使用一個名為Honeyview的軟體打開zip
(因為它可以不必解壓縮便能觀看zip壓縮起來的畫廊)

這導致與電腦預設的啟動程式不同而無法使用您的設定
只要設定 "自定義播放器" 便會無法使用 "自启动播放器"

為了使用不同的撥放器，我也嘗試過設置額外的媒體庫
結果是程序不允許設置多個媒體庫在同一個路徑上，會跳出重複路徑的錯誤訊息

目前我的目標是同一個目錄中
zip > 使用"Honeyviwe"打開
mp4 > 使用"自启动播放器"打開
而Honeyviwe是非系統預設的播放器

不知道大佬目前有沒有解決方式?

**Comment by anobaka** [comment]
目前（<=v1.6.0）没办法支持；
计划v1.6.1支持`子播放器`

**Comment by anobaka** [comment]
相关截图和文档
[sub-player](http://inside-world.anobaka.com/doc#custom-component-player)
