### ISSUE TITLE
用"发布时间"或"文件添加时间"進行篩選的問題

### ISSUE THREAD

**Issue by bennyz327** [anobaka/InsideWorld#190]
大老您好，今天剛發現版本可以使用beta版很興奮，試用後有一些關於時間篩選的問題，狀況如下

問題描述
若在"資源"頁面使用"发布时间"或是"文件添加时间"來進行篩選後
就算後來已經取消"发布时间"或是"文件添加时间"的篩選
下次進入"資源"頁面時還是會維持上次篩選的結果，只能再次手動取消篩選

重現步驟
1.點選到資源頁面
2.點選最上面的"文件添加时间"按鈕，選擇一個時間範圍A進行篩選，頁面會正常的進行篩選
3.點選"文件添加时间"按鈕右上角的紅色叉叉，頁面會正常的取消篩選
4.點選其他頁面，例如"標籤"頁面
5.再次點選"資源"頁面，"資源"頁面會自動呈現步驟2的時間範圍A的篩選結果
(這邊感覺正常的預想狀態應該是沒有進行時間範圍A的篩選結果，因為步驟3已經取消篩選了)

P.S.
1.關閉程序重新啟動也無法重置這個狀況
2.進入這個狀態後重新選擇一個篩選範圍B的話，再次點選"資源"頁面會自動呈現篩選範圍B的結果

版本:
1.6.1-beta

**Comment by bennyz327** [comment]
補充:
使用 "語言"篩選 和 "標籤"篩選 也有相同的狀況

**Comment by anobaka** [comment]
感谢使用~问题已复现，修复中
