### ISSUE TITLE
删除分类后，该分类下之前创建的标签还在，无法删除。

### ISSUE THREAD

**Issue by marcaas** [anobaka/InsideWorld#227]

**Comment by anobaka** [comment]
标签和分类之间无关联关系，删除分类不会影响标签数据；
如果是其他问题导致标签无法删除，请列一下操作步骤和相关UI提示，谢谢

**Comment by marcaas** [comment]
是这样的，给作品打上标签之后，这个标签就进入了总的标签池（就是所有打过的标签的集合），这个标签池，可以在资源页面按各个不同标签查询资源。我的疑问是我可以在作品页面把单个作品的某一标签删掉，但是删掉后，标签池里还是有这个标签，那么这个标签池里的标签该如何删除呢。（不知道说的是不是清楚，现在在外面不是很方便截图，要是没说清楚的话，等我有时间回家给大佬你截一下）

**Comment by anobaka** [comment]
在标签页面删除即可

**Comment by marcaas** [comment]
标签页面没看到有删除的选项，可能是我没找到，我回去再找找，感谢大佬。

**Comment by anobaka** [comment]
哎呀不好意思，上次改版好像把相关功能误删了，1.6.1正式版加回来

**Comment by marcaas** [comment]
哦哦，原来是这样，哈哈，多谢解答。

**Comment by anobaka** [comment]
![image](https://user-images.githubusercontent.com/2888789/183582178-0b1fdf92-f8ba-4721-9080-adc55cbac858.png)
![image](https://user-images.githubusercontent.com/2888789/183582195-ce961843-6540-4273-998d-af3f2e89a39f.png)
![image](https://user-images.githubusercontent.com/2888789/183582222-7f51dfd2-3d1d-4453-9add-19189a6a15e0.png)
![image](https://user-images.githubusercontent.com/2888789/183582236-f495d090-dc9e-40af-b956-b40c8bdcce43.png)
