### ISSUE TITLE
尝试从压缩文件提取封面时，封面有时会选择错误

### ISSUE THREAD

**Issue by huangchunhuiSW** [anobaka/InsideWorld#234]
自动提取封面时，偶尔会提取到不正确的封面。例如有个压缩文档，封面是01_001.jpg，不过程序提取到的是34_033.jpg。建议在从压缩文件提取图片封面时，先对压缩文件的文件名列表做排序，选取第一张作为封面（我用python提取封面也会出现这个情况，在排序后就不会出现了，不知道这边是不是同一个问题）。
另外，是否能做一个功能，直接把同级目录下，与压缩文件同名的jpg或者png文件作为封面，感谢。

**Comment by anobaka** [comment]
> 自动提取封面时，偶尔会提取到不正确的封面。例如有个压缩文档，封面是01_001.jpg，不过程序提取到的是34_033.jpg。建议在从压缩文件提取图片封面时，先对压缩文件的文件名列表做排序，选取第一张作为封面（我用python提取封面也会出现这个情况，在排序后就不会出现了，不知道这边是不是同一个问题）。

这个可以做，可能会有轻微性能损耗。

> 另外，是否能做一个功能，直接把同级目录下，与压缩文件同名的jpg或者png文件作为封面，感谢。

这个可能会导致一个小问题：如果你的文件结构是
```
{媒体库设置的资源目录}
         |---A.zip
         |---A.rar
         |---A.jpg
```
那么A.zip和A.rar这2个资源会使用同一张图片作为封面，在这个基础上，如果使用了【删除封面】功能，会导致2个资源都失去了封面，这样的处理方式能接受吗？
