### ISSUE TITLE
增加cookie相关配置交互

### ISSUE THREAD

**Issue by anobaka** [anobaka/InsideWorld#247]
为确保用户顺利完成首次cookie配置，配置cookie后提供验证功能
- [x] 哔哩哔哩
![image](https://user-images.githubusercontent.com/2888789/188394615-ad3b3512-1dae-453c-b967-ca752df4e54f.png)

- [x] exhentai
![image](https://user-images.githubusercontent.com/2888789/188394055-08cb3c9c-fbc4-46c3-8e58-088ad631f12a.png)

**Comment by bennyz327** [comment]
大老可以請教一下，cookie如何正確讓inside world讀取呢?
我網頁可以正常瀏覽exhentai，試過用餅乾提取器、F12裡面直接複製貼上，都無法讓inside world成功讀取到餅乾
(錯誤訊息都是"message: Cookie is not set")
