### ISSUE TITLE
[Feature Request]在资源库中为资源卡片添加长度限制

### ISSUE THREAD

**Issue by TeoZler** [anobaka/InsideWorld#278]
![image](https://user-images.githubusercontent.com/43093562/200788098-4a891c19-153b-42cc-b46d-821ca0cadfe3.png)
当tag较多时，卡片会变得非常长。
希望能增加对卡片的长度限制相关的可调节配置。
比如当卡片长度超过一定值时，省略后面的tag

**Comment by anobaka** [comment]
采用和名称一样的交互方式，默认显示两行，鼠标悬浮时显示全部
