### ISSUE TITLE
易用性优化建议

### ISSUE THREAD

**Issue by zdrzdr** [anobaka/InsideWorld#343]
从易用性的角度上有几个建议，如果觉得这样一起说不方便的话我就拆分一下issue

1，用户操作和设置界面区隔
当前操作界面对于设置和使用的区隔不是很明显，建议可以从顺序或者层级上进行区隔，比如这样（画的很糙）

![BHGH6XX)@QN(42QFQXM`LKY 拷贝](https://user-images.githubusercontent.com/36026283/221622224-ecd516db-d77a-4ef4-8250-78eb7a285688.png)

![BHGH6XX)@QN(42QFQXM2`LKY](https://user-images.githubusercontent.com/36026283/221622287-c07900ce-a36b-479e-a19f-70102b6e4a28.png)

2，媒体库层级
资源库可以将按分类筛选等常用选项的层级提高一些，目前常用和不常用的筛选都是并列的
甚至在进行设置操作区隔后，不同媒体库可以占据一个大的层级

3，媒体库易用性
媒体库对右键的利用有些不完善，很多功能可以通过右键来展现
建议在评星下面增加一个已看的功能，这样可以让不想评级的时候表示已阅
这是一个文件夹的展示图标和可点击图标没有明显区别，在整个界面里也有些突兀，建议优化下

4，封面的优化
目前资源库对于程序的ico存在大概有一半无法识别，如果可以提取的话管理游戏会很方便
大尺寸浏览图会导致资源库卡顿和加载缓慢，建议增加一个默认创建缩略图的功能
最好可以让用户选择对某个分类进行优化，所有图片生成低分辨率浏览图，打开文件列表的时候会很卡

**Comment by anobaka** [comment]
感谢您使用并提出了很好的建议，待我逐项吸收再细化一下，然后开始研发
