### ISSUE TITLE
鼠标悬浮在资源封面一段时间后，自动预览资源内容

### ISSUE THREAD

**Issue by anobaka** [anobaka/InsideWorld#364]
+ 还需要支持进度条

**Comment by ChrysanLee** [comment]
冲冲冲！！！

**Comment by ChrysanLee** [comment]
如果可以预览取前中后，各2-3秒 就完美了

**Comment by anobaka** [comment]
因为资源封面的区域太小了，实际可操作的进度条的长度可能非常少（可能小于150像素），暂定使用以下规则分配进度条占用情况：
a. 认为一张图片长度=1
b. 认为一个视频长度=总秒数
c. 压缩包使用内部文件总长度
d. 暂不支持音频
e = Σa + Σb + Σc

1. 假设进度条长度为n，当鼠标悬浮在m(0<=m<=n)点时，处于内容f = (m / n * 100)%的位置，通过f反算出对应的文件及内容位置；
2. 鼠标悬停后，自动播放后续内容；
