### ISSUE TITLE
配置標籤增加正則表達式的選項

### ISSUE THREAD

**Issue by bennyz327** [anobaka/InsideWorld#398]
配置媒體庫中的根據路徑配置標籤功能，希望可以增加正則表達式的選項，目前只有兩個選項：
“使用根目录后第1层”和“使用资源路径的前1层”
但是我有很多資源底下會有額外資料夾來表示子資源的性質。

舉例來說：

這是根目錄
/root

這些是被設定為父資源的資料夾
（結構固定）
/root/CreatorA/releaseSet_1/
/root/CreatorA/releaseSet_2/
/root/CreatorA/releaseSet_3/
....

被視為資源的檔案
（結構存在差異）
/root/CreatorA/releaseSet_1/pic1.png
/root/CreatorA/releaseSet_1/pic2.png
/root/CreatorA/releaseSet_1/草圖/01.png
/root/CreatorA/releaseSet_2/animate1.mp4
/root/CreatorA/releaseSet_2/animate2.mp4
/root/CreatorA/releaseSet_2/nosound/animate3.mp4

在上述的結構中，如果想要在添加資源的時候，透過偵測路徑中特定字串加上標籤
例如單獨幫"01.png"加上草圖的標籤，或是單獨幫"animate3.mp4"加上nosound的標籤
以目前的選項似乎無法進行這樣的操作

能不能在選項中，加上正則表達式來配對路徑中的字串，是否就能實現我的想法呢?

程式版本：v1.7.0

**Comment by anobaka** [comment]
优化媒体库路径信息配置规则：
**入口**
![portal](https://github.com/anobaka/InsideWorld/assets/2888789/72b6429f-d1ba-4aed-9ac8-0811d1bffd00)
**简单配置**
![simple](https://github.com/anobaka/InsideWorld/assets/2888789/ed5b9851-9cc9-4832-96d7-fa7588caaba0)
**设置tag a和b**
![ab](https://github.com/anobaka/InsideWorld/assets/2888789/4aef3515-2971-42da-9b52-255253b5e6c7)
**设置tag b和c**
![bc](https://github.com/anobaka/InsideWorld/assets/2888789/740d486e-4f1a-40a1-bb0d-fb441f8ff22b)
**设置tag a、b和c**
![abc](https://github.com/anobaka/InsideWorld/assets/2888789/eba16b82-78f2-4234-b7e5-a5e8652baed6)
**验证结果**
![validation](https://github.com/anobaka/InsideWorld/assets/2888789/ee0c7003-df8c-42d7-a626-3826c9939230)
