### ISSUE TITLE
支持本地网络文件的添加

### ISSUE THREAD

**Issue by SongJF** [anobaka/InsideWorld#399]
现无法选择本地网络中的文件夹作为工作目录
![image](https://github.com/anobaka/InsideWorld/assets/32432963/b3b84677-c94b-4d00-9f4c-d94cca2d014c)

添加分类后，也无法播放或打开文件夹
![image](https://github.com/anobaka/InsideWorld/assets/32432963/5976b19a-229d-484a-91b9-d4a02a5f924e)

**Comment by anobaka** [comment]
后续会支持网络路径，现阶段可以先映射成本地磁盘后再使用
