### ISSUE TITLE
正则匹配不生效

### ISSUE THREAD

**Issue by Ptilopsis01** [anobaka/InsideWorld#436]
如视频所示

https://github.com/anobaka/InsideWorld/assets/93318731/37803acb-0701-4481-a950-f8244a49499d

此外使用自定义属性时会导致资源库同步失败报错
<img width="1281" alt="屏幕截图 2023-08-19 152216" src="https://github.com/anobaka/InsideWorld/assets/93318731/372cbb23-8a67-48bc-ac91-08105da08624">

**Comment by anobaka** [comment]
第一个问题是因为使用了捕获组，捕获组在【资源】属性中不会生效，将会在v1.7.2-beta增加相应的错误提示；
第二个问题将在v1.7.2-beta中修复；

**Comment by Ptilopsis01** [comment]
> 第一个问题是因为使用了捕获组，捕获组在【资源】属性中不会生效，将会在v1.7.2-beta增加相应的错误提示； 第二个问题将在v1.7.2-beta中修复；

好的感谢
