### ISSUE TITLE
进入资源界面时有很大概率出现报错

### ISSUE THREAD

**Issue by Ptilopsis01** [anobaka/InsideWorld#471]
![image](https://github.com/anobaka/InsideWorld/assets/93318731/f5de6670-60df-42e1-a8ac-be17adb4a534)
报错如图所示，没发现什么规律，点进资源界面就有很大概率报错

**Comment by anobaka** [comment]
![image](https://github.com/anobaka/InsideWorld/assets/2888789/02420d3a-fee3-42c3-9a6f-d4e6644e79b3)
现在截图的内容不是很容易查到问题，麻烦按这个方式重试一下看看哈，谢谢

**Comment by Ptilopsis01** [comment]
> ![image](https://private-user-images.githubusercontent.com/2888789/285649176-02420d3a-fee3-42c3-9a6f-d4e6644e79b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDA4OTMsIm5iZiI6MTcwMTAwMDU5MywicGF0aCI6Ii8yODg4Nzg5LzI4NTY0OTE3Ni0wMjQyMGQzYS1mZWUzLTQyYzMtOWE2Zi1kNGU2NjQ0ZTc5YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMTIwOTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ4NmNmNDBhYTRjOGJiOWJkMzJhN2I3NGYwMGE1ZjQ3YmZkMTk5ZDBiZDZjYmRjMTQzNTJjZDgzYmQ3MjFiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0_dJZz4r_ErcfwzcBxbMGeHmqYEhVP4PwgJWm2Yink4) 现在截图的内容不是很容易查到问题，先按下F12，打开控制台，然后麻烦按这个方式重试一下看看哈，谢谢

![image](https://github.com/anobaka/InsideWorld/assets/93318731/1f822d9b-495e-4a6e-a056-d1c45efd09c5)

**Comment by anobaka** [comment]
看起来目前版本没有引入sourcemap，依旧无法获得有效信息，请在1.7.3-beta发布后再尝试以上操作，谢谢

**Comment by anobaka** [comment]
因为目前无法获取比较明确的调试信息，仅通过代码来看，目前可能引发该问题的原因是：搜索条件内包含了已删除的数据。

**临时修复方案**
*如果有重要数据请提前备份该文件*
通过系统配置界面打开`数据保存路径`，编辑其中的`/configs/resource.json`，将`lastSearch`与`searchSlots`移除后，再进入资源列表页面

**Comment by Ptilopsis01** [comment]
> 因为目前无法获取比较明确的调试信息，仅通过代码来看，目前可能引发该问题的原因是：搜索条件内包含了已删除的数据。
> 
> **临时修复方案** _如果有重要数据请提前备份该文件_ 通过系统配置界面打开`数据保存路径`，编辑其中的`/configs/resource.json`，将`lastSearch`与`searchSlots`移除后，再进入资源列表页面

我尝试了一下，资源名称显示的还是dl增强的名称

**Comment by anobaka** [comment]
这个方法解决不了 #472 的问题，只是尝试解决一下本问题，如果没有生效的话，麻烦先等1.7.3-beta发布后再尝试以上的操作，谢谢

> ![image](https://private-user-images.githubusercontent.com/2888789/285649176-02420d3a-fee3-42c3-9a6f-d4e6644e79b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDQxMzAsIm5iZiI6MTcwMTAwMzgzMCwicGF0aCI6Ii8yODg4Nzg5LzI4NTY0OTE3Ni0wMjQyMGQzYS1mZWUzLTQyYzMtOWE2Zi1kNGU2NjQ0ZTc5YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMTMwMzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNhNTY4NzNkYTQyZGQwMTA4ODk0YTE1ZTZjNjhlZjlmMGRhOWEzNTU0ZjBmYzhiZDdjYWE2MTQ0Njk2NDk5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5aewstQXiQwhIU14L_4Ioi2fMD9SfH9c1MWHBpn22Gw) 现在截图的内容不是很容易查到问题，先按下F12，打开控制台，然后麻烦按这个方式重试一下看看哈，谢谢

**Comment by Ptilopsis01** [comment]
> > 因为目前无法获取比较明确的调试信息，仅通过代码来看，目前可能引发该问题的原因是：搜索条件内包含了已删除的数据。
> > **临时修复方案** _如果有重要数据请提前备份该文件_ 通过系统配置界面打开`数据保存路径`，编辑其中的`/configs/resource.json`，将`lastSearch`与`searchSlots`移除后，再进入资源列表页面
> 
> 这个方法解决不了 #472 的问题，只是尝试解决一下本问题，如果该方法没有生效的话，麻烦先等1.7.3-beta发布后再尝试以下的操作，谢谢
> 
> > ![image](https://private-user-images.githubusercontent.com/2888789/285649176-02420d3a-fee3-42c3-9a6f-d4e6644e79b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDQxMzAsIm5iZiI6MTcwMTAwMzgzMCwicGF0aCI6Ii8yODg4Nzg5LzI4NTY0OTE3Ni0wMjQyMGQzYS1mZWUzLTQyYzMtOWE2Zi1kNGU2NjQ0ZTc5YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMTMwMzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNhNTY4NzNkYTQyZGQwMTA4ODk0YTE1ZTZjNjhlZjlmMGRhOWEzNTU0ZjBmYzhiZDdjYWE2MTQ0Njk2NDk5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5aewstQXiQwhIU14L_4Ioi2fMD9SfH9c1MWHBpn22Gw) 现在截图的内容不是很容易查到问题，先按下F12，打开控制台，然后麻烦按这个方式重试一下看看哈，谢谢

哦哦不好意思看串了，不过这个问题也还是会发生

**Comment by anobaka** [comment]
> 因为目前无法获取比较明确的调试信息，仅通过代码来看，目前可能引发该问题的原因是：搜索条件内包含了已删除的数据。
> 
> **临时修复方案** _如果有重要数据请提前备份该文件_ 通过系统配置界面打开`数据保存路径`，编辑其中的`/configs/resource.json`，将`lastSearch`与`searchSlots`移除后，再进入资源列表页面

那只能先等1.7.3-beta出来再尝试debug了，目前盲看下来最大可能性就是这个原因了。

新版本预计几天内发布，麻烦届时再试一下哈，谢谢
