### ISSUE TITLE
部分资源增强优先级出错

### ISSUE THREAD

**Issue by Ptilopsis01** [anobaka/InsideWorld#472]
![image](https://github.com/anobaka/InsideWorld/assets/93318731/dc26a546-39f6-4621-a279-a575b605f911)
![image](https://github.com/anobaka/InsideWorld/assets/93318731/4b807ba1-8931-4db4-bea4-202edd507dc5)
![image](https://github.com/anobaka/InsideWorld/assets/93318731/30abf4ba-1430-4796-8792-7102d7fec1ce)
如图所示，名称的优先级应当是本地大于dl，实际上显示出来依然是dl增强的名称，但只有少数资源出现了该问题，不清楚原因

**Comment by anobaka** [comment]
*A*

如果不是bug，那可能发生该问题的情况是：
1. 当首次增强时，分类仅配置了DLsite增强器；
2. 后续增加本地增强器时，因为`名称`数据不为空，所以不会覆盖，故最终保留第一步的结果；

*B*

如果是bug，因为只有少数资源出现了该问题，可能需要更明确的重现步骤才好查原因；

---------------

预计在1.8.0会对增强进行一些重构，届时所有增强器产生的数据均会保留，并且根据分类配置动态与资源绑定，不会产生*A*中所述的收历史配置影响的问题。如果不着急的话，建议到时再观察。

**Comment by Ptilopsis01** [comment]
> _A_
> 
> 如果不是bug，那可能发生该问题的情况是：
> 
> 1. 当首次增强时，分类仅配置了DLsite增强器；
> 2. 后续增加本地增强器时，因为`名称`数据不为空，所以不会覆盖，故最终保留第一步的结果；
> 
> _B_
> 
> 如果是bug，因为只有少数资源出现了该问题，可能需要更明确的重现步骤才好查原因；
> 
> 预计在1.8.0会对增强进行一些重构，届时所有增强器产生的数据均会保留，并且根据分类配置动态与资源绑定，不会产生_A_中所述的收历史配置影响的问题。如果不着急的话，建议到时再观察。

好的了解了

**Comment by anobaka** [comment]
增强器已重构，新版本已无该问题
