### ISSUE TITLE
希望增加更多内置属性

### ISSUE THREAD

**Issue by Ptilopsis01** [anobaka/InsideWorld#475]
如题，个人认为当前的内置属性有些少了，且比较需要增加用于管理资源状态的属性，参考playnite：
![image](https://github.com/anobaka/InsideWorld/assets/93318731/7611eb4a-ff6c-4595-b08b-634ecd9620f2)
虽然playnite是专职用于游戏管理的，不过我认为其他类型的资源增加这一属性也很有必要

同时考虑到资源的性质，我认为“语言”这一属性的覆盖面并不够，可能还需要“翻译”这一属性，以音声为例，中文音声和日文音声汉化显然不能都简单归于“中文”，但含有汉化的日文作品归于“日文”似乎也不太合适

此外，目前的自定义属性实际上没法手动对特定的资源进行添加或者编辑，不知道是否有改进的计划

**Comment by Ptilopsis01** [comment]
非常感谢！

**Comment by anobaka** [comment]
这里有一个关于目前版本手动编辑资源属性数据的统计，可能会决定是否需要增加历史数据迁移至新版自定义属性的功能，建议有相关需求的同学投个票 #498

**Comment by anobaka** [comment]
*这里是最新的信息*

**自定义属性**
+ [ ] 单行文本、多行文本、链接
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示
+ [ ] 数字、百分比、评分
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示
+ [ ] 单选、多选
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示
+ [ ] 附件
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示
+ [ ] 复选框
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示
+ [ ] 公式
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示
+ [ ] 多级选项
  + [ ] 定义
  + [ ] 配置属性
  + [ ] 搜索
  + [ ] 设置值
  + [ ] 展示

**内置属性**

+ 简单属性仅保留：仅保留`id`，`创建时间`，`更新时间`，`文件创建时间`，`文件修改时间`，`媒体库`，`分类`，`父级资源`
+ 特殊属性仅保留：`标签`，`关联收藏夹`

**功能调整**

+ [ ] 历史属性值&内置属性值迁移
+ [ ] 从自定义属性向另外一个自定义属性复制/迁移已设置的值
+ [ ] 调整增强器增强目标
+ [ ] 调整批量修改功能的筛选条件和处理目标
+ [ ] 调整资源搜索条件
+ [ ] 根据分类配置资源展示名称规则
