### ISSUE TITLE
优化快捷配置代理

### ISSUE THREAD

**Issue by zdrzdr** [anobaka/InsideWorld#497]
希望增加几个默认代理配置选项
提供下拉自动填充菜单
![QQ截图20240317133930](https://github.com/anobaka/InsideWorld/assets/36026283/d19de9a5-1b40-4ccf-85ca-4d0aea74fce9)
![QQ截图20240317133947](https://github.com/anobaka/InsideWorld/assets/36026283/6a38b498-5494-407e-aab2-5dd93846fbf8)

**Comment by anobaka** [comment]
![image](https://github.com/anobaka/InsideWorld/assets/2888789/bacc9222-6f96-4823-968e-35136782e786)
