### ISSUE TITLE
[Bug] 部分资源属性转换出错

### ISSUE THREAD

**Issue by Ptilopsis01** [anobaka/InsideWorld#543]
![image](https://github.com/user-attachments/assets/5693ce1d-9f53-4253-a696-70e0d4ebc1a6)
如图，这里的作者是此前通过javlibrary增强器获取的，在旧版本中显示正常，但这里显示出来是乱码

**Comment by anobaka** [comment]
可以麻烦私发一下bakabase_insideworld.db文件吗？谢谢

**Comment by Ptilopsis01** [comment]
已发
