### ISSUE TITLE
[Bug]新旧版本转换时的增强器与自定义属性相关bug

### ISSUE THREAD

**Issue by Ptilopsis01** [anobaka/InsideWorld#549]
1. 
![image](https://github.com/user-attachments/assets/26035605-0171-4fbf-8fe2-77d762143a71)
如图，出现了部分重复的属性，推测为原本资源有“介绍”这个属性，转换后属性保留了但是在自定义属性中没有“介绍”，所以增强器如果勾选了自动生产就会生成一个新的“简介”属性，如果自己创建一个“介绍”属性再进行绑定，不管如何命名该属性，仍然会在界面中同时出现原本的“介绍”和新的“介绍”属性。对于“评分”属性该问题一样存在。
2. 属性与增强器匹配失败，未获取到对应的内容：
![image](https://github.com/user-attachments/assets/ae3fc259-8d39-4f8f-9792-ee8a1f287c53)
![image](https://github.com/user-attachments/assets/c529e12f-ebba-4ba1-8024-b47f4c51aa77)
3. 属性转换类型时会出现永久丢失，例如将“多选”转换为“多行文本”，此时所有的属性值都没法显示，即使自定义属性面板中的统计数量仍然未变；如果再转换回来，所有的属性值仍然不显示。

**Comment by anobaka** [comment]
后续的beta版本中修复了很多属性转换的问题，先关闭该issue，如果后续再复现请在新开issue。
