### ISSUE TITLE
[Bug] 创建自定义属性未选择类型导致失败

### ISSUE THREAD

**Issue by 2455DD** [anobaka/InsideWorld#633]
**Describe the bug**
创建自定义属性未选择类型导致失败

**To Reproduce**
1. 进入创建自定义属性窗口
2. 不选择任何类型（即默认值），并添加
3. 报错

**Expected behavior**
应该进行“不选择任何类型”的非法行为检查

**Comment by anobaka** [comment]
![image](https://github.com/user-attachments/assets/77187a58-fdfb-4693-8771-bbc1d1bf882e)
在类型和名称非法的情况下，禁用确定按钮

**Comment by anobaka** [comment]
因为该问题会导致几乎所有使用了属性类型的地方报错，临时增加rc2版本
