### ISSUE TITLE
[Feature Request] 支持多正则增强器

### ISSUE THREAD

**Issue by 2455DD** [anobaka/InsideWorld#648]
不同的资源类型通常会使用不同的正则表达式进行管理，需要多个正则增强器进行管理，但在当前版本(v1.9.0-rc3)全局共享一个正则增强器，存在潜在的改进空间。

建议添加一个"增加增强器"的按钮，可以添加数个正则增强器，并且可以对正则增强器进行命名

**Comment by anobaka** [comment]
可以在增强器中设置多个正则，使用多个不同的捕获组名称，然后将这些捕获组分别绑定至需要增强的分类即可。

主要是因为增强器现在是单例的，暂时没有变更为多例的计划。
